### ISSUE TITLE
您好，信鸽SDK已经更新到2.36了，您的这个插件会更新吗？

### ISSUE THREAD

**Issue by lanbomo** [hroze/xinge-cordova#1]
您好，信鸽SDK已经更新到2.36了，您的这个插件会更新吗？还有您的插件信鸽Token怎么获取呢？非常感谢您的分享，帮助了我们只会网页开发，而不会Android开发的人。谢谢！

**Comment by edgora-ai** [comment]
自己用的，因为一直能用，所以没更新

**Comment by edgora-ai** [comment]
请更新3.1.2版本
