### ISSUE TITLE
how to register

### ISSUE THREAD

**Issue by milanjya** [hroze/xinge-cordova#3]
how to register

**Comment by milanjya** [comment]
你好，麻烦问一下怎么调用注册取token？

**Comment by edgora-ai** [comment]
参照 README.md，刚更新了

**Comment by milanjya** [comment]
好的。非常感谢。
另外信鸽目前更新到3.2.2了，新增了几个厂商通道的集成，咱们的插件会更新吗？

**Comment by edgora-ai** [comment]
@milanjya  哈哈 你能否更新一下，最近较忙
